//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
export var RolesEnum;
(function (RolesEnum) {
    RolesEnum[RolesEnum["ADMINISTRADOR"] = 1] = "ADMINISTRADOR";
    RolesEnum[RolesEnum["SUPERVISOR"] = 2] = "SUPERVISOR";
    RolesEnum[RolesEnum["TEACHER"] = 3] = "TEACHER";
    RolesEnum[RolesEnum["DEBUG"] = -1] = "DEBUG";
})(RolesEnum || (RolesEnum = {}));
export var ShiftTimeEnum;
(function (ShiftTimeEnum) {
    ShiftTimeEnum[ShiftTimeEnum["TOMORROW"] = 1] = "TOMORROW";
    ShiftTimeEnum[ShiftTimeEnum["AFTERNOON"] = 2] = "AFTERNOON";
    ShiftTimeEnum[ShiftTimeEnum["NIGHT"] = 3] = "NIGHT";
})(ShiftTimeEnum || (ShiftTimeEnum = {}));
//# sourceMappingURL=schoolmngr.model.js.map